### ISSUE TITLE
Update CircleCI Orb version badge on README

### ISSUE THREAD

**Issue by lucasqueiroz** [sue445/circleci-ruby-orbs#43]
# Description

The README.md features a CircleCI Orb Version badge, but it's currently broken.

**Comment by sue445** [comment]
This is issue of https://badges.circleci.io cert. 

So I reported.

https://discuss.circleci.com/t/certificate-of-https-badges-circleci-io-has-expired/32814

Thank you.

**Comment by sue445** [comment]
Badge has been revived!

![image](https://user-images.githubusercontent.com/608755/66363180-53c62d00-e9c0-11e9-8ac1-a403a4123247.png)
